<?php
# -----------------------------------------------------
# 
# Program: gen-sunposa-lang.php
#
# Purpose: combine separate lang-LL.txt files into one PHP
#          array for sunposa.php to have language translation
#          capabilities for display on the image.
#
# Author:  Ken True - webmaster@saratoga-weather.org
#
# Version 1.00 - 28-Aug-2024 - initial release
# -----------------------------------------------------
# 
$Version = 'gen-sunposa-lang.php V1.02 - 16-Sep-2024';

if ( isset($_REQUEST['sce']) && strtolower($_REQUEST['sce']) == 'view' ) {
//--self downloader --
   $filenameReal = __FILE__;
   $download_size = filesize($filenameReal);
   header('Pragma: public');
   header('Cache-Control: private');
   header('Cache-Control: no-cache, must-revalidate');
   header("Content-type: text/plain");
   header("Accept-Ranges: bytes");
   header("Content-Length: $download_size");
   header('Connection: close');
   
   readfile($filenameReal);
   exit;
}

header('Content-type: text/plain,charset=ISO-8859-1');
date_default_timezone_set('America/Los_Angeles');

$theDate = date('r');

print "$Version\nRun on: $theDate\n";
  
$filelist = glob('./lang-*.txt');
sort($filelist);
$outArray = array();
$outArray['program'] = $Version;
$outArray['generated'] = $theDate;
$outArray['note'] = 'DO NOT EDIT THIS FILE';

foreach ($filelist as $i => $filename) {
  print ".. $filename\n";
  if(preg_match('!lang-(\S+)\.txt!',$filename,$M)) {
    $lang = $M[1];
    $aName = 'trans_'.$lang;
    print "  lang='$lang' aName='$aName'\n";
    include_once($filename);
    $outArray[$lang] = ${'trans_'.$lang}[$lang];
  }
}

$output = '<?php
# -----------------------------------------------------
# 
# Language translations for sunposa.php legends on graph
#
# Author: Ken True - webmaster@saratoga-weather.org
#
# Version 1.00 - 28-Aug-2024 - initial release
# Version 1.01 - 04-Sep-2024 - minor English update
# Version 1.02 - 16-Sep-2024 - minor English update
#
# NOTE: DO NOT EDIT THIS FILE.
#   For character set compatibility
#   ONLY edit the langtrans/lang-LL.txt file using the specified character
#   set encoding in the file using notepad++, then run langtrans/gen-sunposa-lang.php
#   to make a replacement sunposa-lang.php file.
#   Copy the langtrans/sunposa-lang.php to ../sunposa-lang.php to implement
#
'."# Generated: $theDate".'
#
# -----------------------------------------------------

$LanguageLookupArray = ';

$output .= var_export($outArray,true).";\n# End of sunposa-lang.php\n";

file_put_contents('sunposa-lang.php',$output);

print "..Done.\n";